const POST_VERB_POLL = 'poll';
const POST_VERB_STANDARD = 'tweet';
const POST_VERB_LINK = 'link';
const POST_TYPE_STANDARD = 0;
const POST_TYPE_POLL = 1;
const POST_TYPE_LINK = 2;
const MAX_POLLING_ALLOWED = 4;
const MIN_POLLING_ALLOWED = 2;
const MAX_POLLING_CHARACTER_ALLOWED = 25;
const DEFAULT_PROFILE_PIC_PATH =
  'https://res.cloudinary.com/hpjivutj2/image/upload/v1617245336/Frame_66_1_xgvszh.png';
const KEY_ACCESS_TOKEN = 'access_token';
const KEY_REFRESH_TOKEN = 'refresh_token';
export {
  POST_VERB_POLL,
  POST_VERB_STANDARD,
  POST_VERB_LINK,
  POST_TYPE_LINK,
  POST_TYPE_STANDARD,
  POST_TYPE_POLL,
  MAX_POLLING_ALLOWED,
  MIN_POLLING_ALLOWED,
  MAX_POLLING_CHARACTER_ALLOWED,
  DEFAULT_PROFILE_PIC_PATH,
  KEY_ACCESS_TOKEN,
  KEY_REFRESH_TOKEN,
};
