const ANALYTICS_SHARE_POST_FEED_ID = "btn_share"
const ANALYTICS_SHARE_POST_FEED_SCREEN = "feed_screen_btn_share"
const ANALYTICS_SHARE_POST_PROFILE_ID = "btn_share"
const ANALYTICS_SHARE_POST_PROFILE_SCREEN = "profile_screen_btn_share"
const ANALYTICS_SHARE_POST_TOPIC_ID = "btn_share"
const ANALYTICS_SHARE_POST_TOPIC_SCREEN = "topic_screen_btn_share"
const CHANNEL_TYPE_GROUP = 1;
const CHANNEL_TYPE_GROUP_LOCATION = 2;
const CHANNEL_TYPE_PERSONAL = 0;
const CHANNEL_TYPE_TOPIC = 3;
const DEFAULT_PROFILE_PIC_PATH = 'https://res.cloudinary.com/hpjivutj2/image/upload/v1617245336/Frame_66_1_xgvszh.png';
const KEY_ACCESS_TOKEN = 'access_token';
const KEY_REFRESH_TOKEN = 'refresh_token';
const MAX_POLLING_ALLOWED = 4;
const MAX_POLLING_CHARACTER_ALLOWED = 25;
const MIN_POLLING_ALLOWED = 2;
const POST_TYPE_LINK = 2;
const POST_TYPE_POLL = 1;
const POST_TYPE_STANDARD = 0;
const POST_VERB_LINK = 'link';
const POST_VERB_POLL = 'poll';
const POST_VERB_STANDARD = 'tweet';

export {
  ANALYTICS_SHARE_POST_FEED_ID,
  ANALYTICS_SHARE_POST_FEED_SCREEN,
  ANALYTICS_SHARE_POST_PROFILE_ID,
  ANALYTICS_SHARE_POST_PROFILE_SCREEN,
  ANALYTICS_SHARE_POST_TOPIC_ID,
  ANALYTICS_SHARE_POST_TOPIC_SCREEN,
  CHANNEL_TYPE_GROUP_LOCATION,
  CHANNEL_TYPE_GROUP,
  CHANNEL_TYPE_PERSONAL,
  CHANNEL_TYPE_TOPIC,
  DEFAULT_PROFILE_PIC_PATH,
  KEY_ACCESS_TOKEN,
  KEY_REFRESH_TOKEN,
  MAX_POLLING_ALLOWED,
  MAX_POLLING_CHARACTER_ALLOWED,
  MIN_POLLING_ALLOWED,
  POST_TYPE_LINK,
  POST_TYPE_POLL,
  POST_TYPE_STANDARD,
  POST_VERB_LINK,
  POST_VERB_POLL,
  POST_VERB_STANDARD,
};
