const MAX_POLLING_ALLOWED = 4
const MIN_POLLING_ALLOWED = 2
const MAX_POLLING_CHARACTER_ALLOWED = 25
const DEFAULT_PROFILE_PIC_PATH = "https://res.cloudinary.com/hpjivutj2/image/upload/v1617245336/Frame_66_1_xgvszh.png"

export {
    MAX_POLLING_ALLOWED,
    MIN_POLLING_ALLOWED,
    MAX_POLLING_CHARACTER_ALLOWED,
    DEFAULT_PROFILE_PIC_PATH
}