require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)

      if text != replace
          puts "Fix: " + name
          system("chmod +w " + name)
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

target 'BetterSocial' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  # use_react_native!(:path => config["reactNativePath"], :hermes_enabled => true)

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'BetterSocialTests' do
    inherit! :complete
    # Pods for testing
  end
  target 'BetterSocialDev' do
    config = use_native_modules!
    permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    pod 'react-native-flipper', path: '../node_modules/react-native-flipper'
    use_react_native!(:path => config["reactNativePath"])

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    end
  target 'BetterSocialStaging' do
    config = use_native_modules!
    permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

    use_react_native!(:path => config["reactNativePath"])

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  use_flipper!
  # use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })
  post_install do |installer|
    flipper_post_install(installer)
    react_native_post_install(installer)

    find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
          "  atomic_notify_one(state);", "  folly::atomic_notify_one(state);")
#     remove_duplicated_frameworks('Pods-BetterSocial', installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end
  end
end

target 'BetterSocial-tvOS' do
  # Pods for BetterSocial-tvOS

  target 'BetterSocial-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
end
