export const SET_DATA_HUMAN_ID = 'SET_DATA_HUMAN_ID';
export const SET_DATA_IMAGE = 'SET_DATA_IMAGE';
export const SET_DATA_USERNAME = 'SET_DATA_USERNAME';
export const SET_LOCAL_COMUNITY = 'SET_LOCAL_COMUNITY';
